
HEADERS = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36"}
DATASET_URL = "https://www.omicsdi.org/ws/dataset"
MERGE_URL = "https://www.omicsdi.org/ws/dataset/merge"
DATASET_PAGE_URL = "https://www.omicsdi.org/ws/dataset/getDatasetPage"
UNMERGE_URL = "https://www.omicsdi.org/ws/dataset/unmerge"
MERGE_CANDIDATE_URL = "https://www.omicsdi.org/ws/dataset/getMergeCandidates"
MULTIOMICS_MERGE_URL = "https://www.omicsdi.org/ws/dataset/multiomicsMerge"
ALL_MERGE_URL = "https://www.omicsdi.org/ws/dataset/getAllmerged"
DATASET_BY_URL_URL = "https://www.omicsdi.org/ws/dataset/getDatasetByUrl"
ALL_URL = "https://www.omicsdi.org/ws/dataset/getAll"
MERGE_CANDIDATE_COUNT_URL = "https://www.omicsdi.org/ws/dataset/getMergeCandidateCount"
SKIP_MERGE_URL = "https://www.omicsdi.org/ws/dataset/skipMerge"
DB_DATABASE_COUNT_URL = "https://www.omicsdi.org/ws/dataset/getDbDatasetCount"
SEARCH_URL = "https://www.omicsdi.org/ws/dataset/search"
LATEST_URL = "https://www.omicsdi.org/ws/dataset/latest"
GET_URL = "https://www.omicsdi.org/ws/dataset/get"
SIMILAR_BY_PUBMED_URL = "https://www.omicsdi.org/ws/dataset/getSimilarByPubmed"
BATCH_URL = "https://www.omicsdi.org/ws/dataset/batch"
MOST_ACCESSED_DATASETS = "https://www.omicsdi.org/ws/dataset/mostAccessed"
FILE_LINKS_URL = "https://www.omicsdi.org/ws/dataset/getFileLinks"
SIMILAR_URL = "https://www.omicsdi.org/ws/dataset/getSimilar"
SAVE_MAPPING_URL = "https://www.omicsdi.org/ws/dblucene/saveMapping"
LUCENE_NAME_URL = "https://www.omicsdi.org/ws/dblucene/getLuceneName"
MAPPINGS_URL = "https://www.omicsdi.org/ws/dblucene/getAllMappings"
DB_NAME_URL = "https://www.omicsdi.org/ws/dblucene/getDbName"
SYNONYMS_URL = "https://www.omicsdi.org/ws/enrichment/getSynonymsForDataset"
REANALYSIS_URL = "https://www.omicsdi.org/ws/enrichment/getSynonymsForDataset"
ENRICHMENT_URL = "https://www.omicsdi.org/ws/enrichment/getEnrichmentInfo"
SIMILAR_DATASETS_BIOLOGY_URL = "https://www.omicsdi.org/ws/enrichment/getSimilarDatasetsByBiologicalData"
SIMILAR_INFO_URL = "https://www.omicsdi.org/ws/enrichment/getSimilarityInfo"

FEEDBACK_URL = "https://www.omicsdi.org/ws/feedback/saveFeedback"
ALL_FEEDBACK_URL = "https://www.omicsdi.org/ws/feedback/getAllFeedbacks"
FEEDBACK_BY_STATUS_URL = "https://www.omicsdi.org/ws/feedback/getFeedbackByStatus"
LIST_URL = "https://www.omicsdi.org/ws/publication/list"
SEO_URL = "https://www.omicsdi.org/ws/seo/home"
SEO_SEARCH_URL = "https://www.omicsdi.org/ws/seo/search"
SEO_API_URL = "https://www.omicsdi.org/ws/seo/api"
SEO_SCHEMA_URL = "https://www.omicsdi.org/ws/seo/schema"
SEO_DATABASE_URL = "https://www.omicsdi.org/ws/seo/database"
SEO_DATASET_URL = "https://www.omicsdi.org/ws/seo/dataset"
SEO_ABOUT_URL = "https://www.omicsdi.org/ws/seo/about"
STATISTICS_URL = "https://www.omicsdi.org/ws/statistics/"
TERM_BY_PATTERN_URL = "https://www.omicsdi.org/ws/term/getTermByPattern"
FREQUENTLY_TERM_URL = "https://www.omicsdi.org/ws/term/frequentlyTerm/list"
DATABASE_URL = "https://www.omicsdi.org/ws/database"
DATABASE_ALL_URL = "https://www.omicsdi.org/ws/database/all"
DATABASE_PICTURE_URL = "https://www.omicsdi.org/ws/database/db/picturebyte"



